on: workflow_dispatch
jobs:
  opa:
    name: opa tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run opa test
      uses: shuanglu/action-opa-shuanglu@shuanglu/deprecate-set-output-command
      with:
        files: .policy/opa.yaml
        coverage: 90%
      id: opa
    - name: Echo output
      if: steps.opa.outputs.result
      run: |
        echo "output exists"
